(function(g){var window=this;var aEa=function(a,b){return g.Xb(a,b)},b6=function(a){g.Dn(a,"zx",g.xc());
return a},c6=function(a,b,c){g.Fa(c)||(c=[String(c)]);
g.Gn(a.o,b,c)},bEa=function(a,b){var c=[];
g.ql(b,function(a){try{var b=g.eE.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.za(b)?g.dE(b)&&c.push(a):c.push(a)},a);
return c},cEa=function(a,b){var c=bEa(a,b);
(0,g.C)(c,function(a){g.eE.prototype.remove.call(this,a)},a)},dEa=function(a){if(a.Nd){if(a.Nd.locationOverrideToken)return{locationOverrideToken:a.Nd.locationOverrideToken};
if(null!=a.Nd.latitudeE7&&null!=a.Nd.longitudeE7)return{latitudeE7:a.Nd.latitudeE7,longitudeE7:a.Nd.longitudeE7}}return null},eEa=function(a,b,c,d){var e=new g.un(null,void 0);
a&&g.vn(e,a);b&&g.wn(e,b);c&&g.xn(e,c);d&&g.yn(e,d);return e},d6=function(a,b){g.XE[a]=!0;
var c=g.VE();c&&c.publish.apply(c,arguments);g.XE[a]=!1},e6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.on;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",fEa(this,a.capabilities||""),gEa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},fEa=function(a,b){a.capabilities.clear();
(0,g.pe)(b.split(","),g.La(aEa,hEa)).forEach(function(b){a.capabilities.add(b)})},gEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},f6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},g6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},iEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},jEa=function(a){return new f6(a)},kEa=function(a){return g.Fa(a)?(0,g.I)(a,jEa):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return g.Fa(a)?"["+(0,g.I)(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},lEa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},k6=function(a,b){return g.Sa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},l6=function(a,b){return g.Sa(a,function(a){return g6(a,b)})},mEa=function(){var a=(0,g.hI)();
a&&cEa(a,a.o.ce(!0))},m6=function(){var a=g.kI("yt-remote-connected-devices")||[];
g.rb(a);return a},nEa=function(a){if(g.Xa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},oEa=function(a){g.jI("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.kI("yt-remote-device-id");a||(a=j6(),g.jI("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.Wa(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.Wa(a,b);g.mI()&&g.tb(a,b);a=nEa(a);if(g.Xa(a))try{g.HH("remote_sid")}catch(c){}else try{g.GH("remote_sid",a.join(","),-1)}catch(c){}},pEa=function(){return g.kI("yt-remote-session-browser-channel")},qEa=function(){return g.kI("yt-remote-local-screens")||[]},rEa=function(){g.jI("yt-remote-lounge-token-expiration",!0,86400)},sEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(qEa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.Mj)(c,function(a){return!g.Wa(b,a)})&&rEa();
g.jI("yt-remote-local-screens",a,31536E3)},tEa=function(a,b){g.jI("yt-remote-session-browser-channel",a);
g.jI("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.Wa(c,d)||c.push(d);oEa(c);p6()},q6=function(a){a||(g.lI("yt-remote-session-screen-id"),g.lI("yt-remote-session-video-id"));
p6();a=m6();g.ab(a,o6());oEa(a)},uEa=function(){if(!r6){var a=g.pE();
a&&(r6=new g.ZD(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},s6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},vEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?wEa(a.shift(),function(){t6(a)}):u6()},xEa=function(a){return"chrome-extension://"+a+v6},wEa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=vEa();
a&&a(!1,"No cast extension found")},zEa=function(){if(yEa){var a=2,b=vEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;wEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},AEa=function(){zEa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+v6,"//www.gstatic.com/eureka/clank"+v6])},w6=function(a,b,c){g.J.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.Gd=b;this.D=(0,g.A)(this.gL,this);this.o=!1;this.A=0;this.B=this.Ia=null;this.C=[]},x6=function(){},y6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.Kn(this);this.A=new g.Rg;this.A.setInterval(250)},CEa=function(a,b,c){a.Wj=1;
a.zh=b6(b.clone());a.ij=c;a.D=!0;BEa(a,null)},z6=function(a,b,c,d,e){a.Wj=1;
a.zh=b6(b.clone());a.ij=null;a.D=c;e&&(a.JF=!1);BEa(a,d)},BEa=function(a,b){a.Sk=(0,g.H)();
A6(a);a.Yh=a.zh.clone();c6(a.Yh,"t",a.F);a.Un=0;a.Vc=a.o.Pt(a.o.Mn()?b:null);0<a.yu&&(a.Xq=new g.Zl((0,g.A)(a.ZG,a,a.Vc),a.yu));a.Y.X(a.Vc,"readystatechange",a.lV);var c=a.Gi?g.hc(a.Gi):{};a.ij?(a.Xr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Vc.send(a.Yh,a.Xr,a.ij,c)):(a.Xr="GET",a.JF&&!g.de&&(c.Connection="close"),a.Vc.send(a.Yh,a.Xr,null,c));a.o.zf(1)},FEa=function(a,b,c){for(var d=!0;!a.mi&&a.Un<c.length;){var e=DEa(a,c);
if(e==B6){4==b&&(a.Ah=4,C6(15),d=!1);break}else if(e==EEa){a.Ah=4;C6(16);d=!1;break}else D6(a,e)}4==b&&0==c.length&&(a.Ah=1,C6(17),d=!1);a.Ff=a.Ff&&d;d||(E6(a),F6(a))},DEa=function(a,b){var c=a.Un,d=b.indexOf("\n",c);
if(-1==d)return B6;c=Number(b.substring(c,d));if(isNaN(c))return EEa;d+=1;if(d+c>b.length)return B6;var e=b.substr(d,c);a.Un=d+c;return e},HEa=function(a,b){a.Sk=(0,g.H)();
A6(a);var c=b?window.location.hostname:"";a.Yh=a.zh.clone();g.Dn(a.Yh,"DOMAIN",c);g.Dn(a.Yh,"t",a.F);try{a.Hf=new ActiveXObject("htmlfile")}catch(n){E6(a);a.Ah=7;C6(22);F6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in G6)k=G6[l];else if(l in GEa)k=G6[l]=GEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
G6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Gd(g.Uc("b/12014412"),d+"</body></html>");a.Hf.open();a.Hf.write(g.ud(c));a.Hf.close();a.Hf.parentWindow.m=(0,g.A)(a.rU,a);a.Hf.parentWindow.d=(0,g.A)(a.UE,a,!0);a.Hf.parentWindow.rpcClose=(0,g.A)(a.UE,a,!1);c=a.Hf.createElement("DIV");a.Hf.parentWindow.document.body.appendChild(c);d=g.hd(a.Yh.toString());d=g.sc(g.ed(d));d=g.Gd(g.Uc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Cd(c,g.ud(d));a.o.zf(1)},A6=function(a){a.my=(0,g.H)()+
a.C;
IEa(a,a.C)},IEa=function(a,b){if(null!=a.vl)throw Error("WatchDog timer not null");
a.vl=H6((0,g.A)(a.GU,a),b)},I6=function(a){a.vl&&(g.v.clearTimeout(a.vl),a.vl=null)},F6=function(a){a.o.EB()||a.mi||a.o.Fq(a)},E6=function(a){I6(a);
g.Df(a.Xq);a.Xq=null;a.A.stop();g.Qn(a.Y);if(a.Vc){var b=a.Vc;a.Vc=null;b.abort();b.dispose()}a.Hf&&(a.Hf=null)},D6=function(a,b){try{a.o.NE(a,b),a.o.zf(4)}catch(c){}},KEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;JEa(a,b,function(e){e?c(!0):g.v.setTimeout(function(){KEa(a,b,c,d,f)},f)})}},JEa=function(a,b,c){var d=new Image;
d.onload=function(){try{J6(d),c(!0)}catch(e){}};
d.onerror=function(){try{J6(d),c(!1)}catch(e){}};
d.onabort=function(){try{J6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{J6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},J6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},LEa=function(a){this.o=a;
this.A=new x6},MEa=function(a){var b=K6(a.o,a.Ml,"/mail/images/cleardot.gif");
b6(b);KEa(b.toString(),5E3,(0,g.A)(a.hK,a),3,2E3);a.zf(1)},M6=function(a){var b=a.o.J;
if(null!=b)C6(5),b?(C6(11),L6(a.o,a,!1)):(C6(12),L6(a.o,a,!0));else if(a.oe=new y6(a,void 0,void 0,void 0),a.oe.Gi=a.wu,b=a.o,b=K6(b,b.Mn()?a.Dm:null,a.xu),C6(5),!g.be||g.Mc(10))c6(b,"TYPE","xmlhttp"),z6(a.oe,b,!1,a.Dm,!1);else{c6(b,"TYPE","html");var c=a.oe;a=!!a.Dm;c.Wj=3;c.zh=b6(b.clone());HEa(c,a)}},N6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new x6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},NEa=function(a,b){this.o=a;
this.map=b;this.context=null},OEa=function(a){g.Ff.call(this,"statevent",a)},PEa=function(a,b){g.Ff.call(this,"timingevent",a);
this.size=b},QEa=function(a){g.Ff.call(this,"serverreachability",a)},TEa=function(a){REa(a);
if(3==a.o){var b=a.un++,c=a.gp.clone();g.Dn(c,"SID",a.B);g.Dn(c,"RID",b);g.Dn(c,"TYPE","terminate");O6(a,c);b=new y6(a,a.B,b,void 0);b.Wj=2;b.zh=b6(c.clone());(new Image).src=b.zh;b.Sk=(0,g.H)();A6(b)}SEa(a)},UEa=function(a){a.EK(1,0);
a.gp=K6(a,null,a.vu);P6(a)},REa=function(a){a.oh&&(a.oh.abort(),a.oh=null);
a.Ac&&(a.Ac.cancel(),a.Ac=null);a.Eg&&(g.v.clearTimeout(a.Eg),a.Eg=null);Q6(a);a.ie&&(a.ie.cancel(),a.ie=null);a.th&&(g.v.clearTimeout(a.th),a.th=null)},VEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new NEa(a.fQ++,b));2!=a.o&&3!=a.o||P6(a)},P6=function(a){a.ie||a.th||(a.th=H6((0,g.A)(a.TE,a),0),a.Nj=0)},XEa=function(a,b){if(1==a.o){if(!b){a.un=Math.floor(1E5*Math.random());
var c=a.un++,d=new y6(a,"",c,void 0);d.Gi=null;var e=R6(a),f=a.gp.clone();g.Dn(f,"RID",c);g.Dn(f,"CVER","1");O6(a,f);CEa(d,f,e);a.ie=d;a.o=2}}else 3==a.o&&(b?WEa(a,b):0==a.A.length||a.ie||WEa(a))},WEa=function(a,b){if(b)if(6<a.pi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.un-1;var d=R6(a)}else c=b.G,d=b.ij;else c=a.un++,d=R6(a);var e=a.gp.clone();g.Dn(e,"SID",a.B);g.Dn(e,"RID",c);g.Dn(e,"AID",a.qk);O6(a,e);c=new y6(a,a.B,c,a.Nj+1);c.Gi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ie=c;CEa(c,e,d)},O6=function(a,b){if(a.Fd){var c=a.Fd.jB();
c&&g.Lb(c,function(a,c){g.Dn(b,c,a)})}},R6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.pi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.pi?e:f-d;try{g.Lb(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},YEa=function(a){a.Ac||a.Eg||(a.G=1,a.Eg=H6((0,g.A)(a.SE,a),0),a.Ej=0)},S6=function(a){if(a.Ac||a.Eg||3<=a.Ej)return!1;
a.G++;a.Eg=H6((0,g.A)(a.SE,a),ZEa(a,a.Ej));a.Ej++;return!0},L6=function(a,b,c){a.Ur=c;
a.Uf=b.Rg;a.F||UEa(a)},Q6=function(a){null!=a.si&&(g.v.clearTimeout(a.si),a.si=null)},ZEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},T6=function(a,b){if(2==b||9==b){var c=null;
a.Fd&&(c=null);var d=(0,g.A)(a.eW,a);c||(c=new g.un("//www.google.com/images/cleardot.gif"),b6(c));JEa(c.toString(),1E4,d)}else C6(2);$Ea(a,b)},$Ea=function(a,b){a.o=0;
a.Fd&&a.Fd.gA(b);SEa(a);REa(a)},SEa=function(a){a.o=0;
a.Uf=-1;if(a.Fd)if(0==a.C.length&&0==a.A.length)a.Fd.Bt();else{g.fb(a.C);var b=g.fb(a.A);a.C.length=0;a.A.length=0;a.Fd.Bt(b)}},K6=function(a,b,c){var d=g.En(c);
if(""!=d.A)b&&g.wn(d,b+"."+d.A),g.xn(d,d.D);else{var e=window.location;d=eEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.fm&&g.Lb(a.fm,function(a,b){g.Dn(d,b,a)});
g.Dn(d,"VER",a.pi);O6(a,d);return d},H6=function(a,b){if(!g.Ha(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},C6=function(a){U6.dispatchEvent(new OEa(U6,a))},aFa=function(){},bFa=function(a,b){this.action=a;
this.params=b||{}},V6=function(a,b){g.J.call(this);
this.o=new g.U(this.hU,0,this);g.K(this,this.o);this.Gd=5E3;this.A=0;if(g.Ha(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ha(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},W6=function(a,b,c){this.K=a;
this.F=b;this.B=new g.YD;this.A=new V6(this.JW,this);this.o=this.kb=null;this.Cb=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.L=c||!1},cFa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Ur,sessionId:a.o.B,arrayId:a.o.qk}},dFa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&XEa(a.o),TEa(a.o));a.H=0},X6=function(a){return!!a.o&&3==a.o.o},eFa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Y6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||document.location.href;var b=g.fh(a)||"";b&&(this.port=":"+b);this.domain=g.eh(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.A=!1))},Z6=function(a,b){var c=a.o;
if(g.za(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.oh(c+b,{})},$6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.La(a.C,d,!0),onError:g.La(a.B,e),Kd:g.La(a.D,e)};c&&(a.Sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.EF(b,a)},iFa=function(){var a=fFa;
gFa();a7.push(a);hFa(a7)},b7=function(a,b){gFa();
var c=a7,d=jFa(a,String(b));g.Xa(c)?kFa(d):(hFa(c),(0,g.C)(c,function(a){a(d)}))},gFa=function(){a7||(a7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ca("yt.mdx.remote.debug.handlers_",a7,void 0))},kFa=function(a){var b=(c7+1)%50;
c7=b;d7[b]=a;e7||(e7=49==b)},hFa=function(a){var b=d7;
if(b[0]){var c=c7,d=e7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
d7=Array(50);c7=-1;e7=!1}},jFa=function(a,b){var c=((0,g.H)()-lFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},f7=function(a){g.V.call(this);
this.G=a;this.o=[]},mFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},nFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.pe)(a.o,function(a){return!!k6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=mFa(a,b[d])||c;return c},oFa=function(a,b){var c=a.o.length;
a.o=(0,g.pe)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},g7=function(a,b,c,d){g.V.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ia=NaN},i7=function(a){f7.call(this,"LocalScreenService");
this.B=a;this.A=NaN;h7(this);this.info("Initializing with "+i6(this.o))},pFa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=Z6(a.B,"/pairing/get_lounge_token_batch");
$6(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.uL,a),(0,g.A)(a.tL,a))}},h7=function(a){var b=kEa(qEa());
b=(0,g.pe)(b,function(a){return!a.uuid});
return nFa(a,b)},j7=function(a,b){sEa((0,g.I)(a.o,iEa));
b&&rEa()},l7=function(a,b){g.V.call(this);
this.F=b;var c=g.kI("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Wa(c,l)}this.o=d;this.D=a;this.B=this.C=NaN;this.A=null;k7("Initialized with "+g.Xg(this.o))},qFa=function(a,b,c){var d=Z6(a.D,"/pairing/get_screen_availability");
$6(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},m7=function(a,b){a:if(g.Rb(b)!=g.Rb(a.o))var c=!1;
else{c=g.Ub(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(k7("Updated online screens: "+g.Xg(a.o)),a.o=b,a.V("screenChange"));rFa(a)},n7=function(a){isNaN(a.B)||g.UE(a.B);
a.B=g.SE((0,g.A)(a.ix,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},k7=function(a){b7("OnlineScreenService",a)},sFa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},rFa=function(a){a=g.Ub(g.Mb(a.o,function(a){return a}));
g.rb(a);a.length?g.jI("yt-remote-online-screen-ids",a.join(","),60):g.lI("yt-remote-online-screen-ids")},o7=function(a){f7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};tFa(this)},vFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.ze();if(k=(c?l6(k,c):null)||l6(k,b)){k.uuid=b;var l=p7(a,k);qFa(a.A,l,function(a){e(a?l:null)})}else c?uFa(a,c,(0,g.A)(function(a){var f=p7(this,new f6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));qFa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},wFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},uFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.EF(Z6(a.F,"/pairing/get_lounge_token_batch"),e)},xFa=function(a){a.o=a.B.ze();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.o))},tFa=function(a){q7(a);
a.B=new i7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.IL,a));xFa(a);a.C=kEa(g.kI("yt-remote-automatic-screen-cache")||[]);q7(a);a.info("Initializing automatic screens: "+i6(a.C));a.A=new l7(a.F,(0,g.A)(a.ze,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},p7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.jI("yt-remote-automatic-screen-cache",(0,g.I)(a.C,iEa)));q7(a);a.D[b.uuid]=b.id;g.jI("yt-remote-device-id-map",a.D,31536E3);return b},q7=function(a){a.D=g.kI("yt-remote-device-id-map")||{}},r7=function(a,b,c){g.V.call(this);
this.R=c;this.J=a;this.A=b;this.B=null},s7=function(a,b){b7(a.R,b)},t7=function(a,b){r7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.PW,this);this.D=(0,g.A)(this.SU,this);this.C=g.SE((0,g.A)(function(){yFa(this,null)},this),12E4)},zFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Xg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.A)(function(){s7(this,"Failed to send message: getMdxSessionStatus.")},a)):s7(a,"Sending yt message without session: "+g.Xg(b))},yFa=function(a,b){g.UE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.Gq,a),d=(0,g.A)(a.Ee,a);a.uB(b,c,d,5)}}else a.Ee(Error("Waiting for session status timed out."))},u7=function(a,b,c){r7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.N=c;this.D=null;this.G=g.y;this.F=NaN;this.L=(0,g.A)(this.SW,this);this.o=g.y},AFa=function(a){a.o=a.J.dH(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.y;
this.Gq(a)},a),(0,g.A)(function(a){this.o=g.y;
this.Ee(a)},a))},BFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.N;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}uEa()&&(b.env_useStageMdx=1);return g.mh(b)},v7=function(a,b){r7.call(this,a,b,"ManualSession");
this.o=g.SE((0,g.A)(this.tk,this,null),150)},w7=function(a,b,c,d){g.V.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.qT,this)},CFa=function(a,b){return b?g.Sa(a.B,function(a){return g6(b,a.label)},a):null},x7=function(a){b7("Controller",a)},fFa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},y7=function(a){return a.D||!!a.B.length||!!a.o},z7=function(a,b,c){b!=a.o&&(g.Df(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.QE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.tk(null)):a.V("yt-remote-cast2-session-change",null))},DFa=function(a){var b=a.A.cH(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&g6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=CFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},JFa=function(a,b,c,d,e,f,k){EFa()?FFa(b,e,f,k)&&(B7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?GFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?GFa(a,c):(C7("Failed to load cast API: "+d),D7(!1),B7(!1),g.lI("yt-remote-cast-available"),g.lI("yt-remote-cast-receiver"),HFa(),c(!1))},d?g.eF("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?AEa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(zEa(),t6(IFa.map(xEa))))):A7("Cannot initialize because not running Chrome")},HFa=function(){A7("dispose");
var a=E7();a&&a.dispose();g.Ca("yt.mdx.remote.cloudview.instance_",null,void 0);KFa(!1);g.$E(F7);F7.length=0},G7=function(){return!!g.kI("yt-remote-cast-installed")},LFa=function(){var a=g.kI("yt-remote-cast-receiver");
return a?a.friendlyName:null},MFa=function(){A7("clearCurrentReceiver");
g.lI("yt-remote-cast-receiver")},NFa=function(){return G7()?E7()?E7().getCastSession():(C7("getCastSelector: Cast is not initialized."),null):(C7("getCastSelector: Cast API is not installed!"),null)},I7=function(){G7()?E7()?H7()?(A7("Requesting cast selector."),E7().requestSession()):(A7("Wait for cast API to be ready to request the session."),F7.push(g.ZE("yt-remote-cast2-api-ready",I7))):C7("requestCastSelector: Cast is not initialized."):C7("requestCastSelector: Cast API is not installed!")},J7=
function(a,b){H7()?E7().setConnectedScreenStatus(a,b):C7("setConnectedScreenStatus called before ready.")},EFa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.IL||a},OFa=function(a,b){E7().init(a,b)},FFa=function(a,b,c,d){var e=!1;
E7()||(a=new w7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.jI("yt-remote-cast-available",a);d6("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){A7("onReceiverSelected: "+a.friendlyName);
g.jI("yt-remote-cast-receiver",a);d6("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){A7("onReceiverResumed: "+a.friendlyName);
g.jI("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){A7("onSessionChange: "+h6(a));
a||g.lI("yt-remote-cast-receiver");d6("yt-remote-cast2-session-change",a)}),g.Ca("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
A7("cloudview.createSingleton_: "+e);return e},E7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},GFa=function(a,b){D7(!0);
B7(!1);OFa(a,function(a){a?(KFa(!0),g.bF("yt-remote-cast2-api-ready")):(C7("Failed to initialize cast API."),D7(!1),g.lI("yt-remote-cast-available"),g.lI("yt-remote-cast-receiver"),HFa());b(a)})},A7=function(a){b7("cloudview",a)},C7=function(a){b7("cloudview",a)},D7=function(a){A7("setCastInstalled_ "+a);
g.jI("yt-remote-cast-installed",a)},H7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},KFa=function(a){A7("setApiReady_ "+a);
g.Ca("yt.mdx.remote.cloudview.apiReady_",a,void 0)},B7=function(a){g.Ca("yt.mdx.remote.cloudview.initializing_",a,void 0)},K7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.D=0;this.o=null;this.hasNext=this.Yf=!1;this.J=this.G=this.F=this.B=0;this.A=NaN;this.H=!1;this.reset(a)},L7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Yf=!1;a.hasNext=!1;a.D=0;a.C=(0,g.H)();a.B=0;a.F=0;a.G=0;a.J=0;a.A=NaN;a.H=!1},M7=function(a){return a.tb()?((0,g.H)()-a.C)/1E3:0},N7=function(a,b){a.D=b;
a.C=(0,g.H)()},O7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.C)/1E3+a.D;
case -1E3:return 0}return a.D},P7=function(a){return a.H?a.F+M7(a):a.F},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&L7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ic(a.o);b.hasPrevious=a.Yf;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.C;b.seekableStart=a.B;b.seekableEnd=a.F;b.duration=a.G;b.loadedTime=a.J;b.liveIngestionTime=a.A;return b},T7=function(a,b){g.V.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.oD;this.B=this.A=null;this.J=(0,g.A)(this.PQ,this);this.G=(0,g.A)(this.xn,this);this.H=(0,g.A)(this.OQ,this);this.K=(0,g.A)(this.bR,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.yy,this),PFa(this))):c=3;0!=c&&(b?this.yy(c):g.SE((0,g.A)(function(){this.yy(c)},this),0));
var d=NFa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new K7(a.C.getPlayerContextData())},PFa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.La(this.lT,a),this))},a)},QFa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},V7=function(a,b){50>a.D.Ic()&&g.qD(a.D,b)},X7=function(a,b,c){var d=U7(a);
N7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.C.sendMessage(b,c)},W7=function(a,b){QFa(a);
a.C.setPlayerContextData(R7(b));PFa(a)},S7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.xn(null));
a.B=b;a.B&&(b7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.xn(a.B.media[0]))},RFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&b7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;N7(d,a.A.getEstimatedTime());W7(a,d)}else b7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.A)(function(a){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.V.call(this);
this.D=NaN;this.N=!1;this.K=this.J=this.L=this.R=NaN;this.T=[];this.C=this.G=this.B=this.qb=this.o=null;this.sa=a;this.T.push(g.GG(window,"beforeunload",(0,g.A)(this.kL,this)));this.A=[];this.qb=new K7;this.aa=b.id;this.o=SFa(this,c);this.o.subscribe("handlerOpened",this.TQ,this);this.o.subscribe("handlerClosed",this.QQ,this);this.o.subscribe("handlerError",this.RQ,this);this.o.subscribe("handlerMessage",this.SQ,this);eFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=this.qb.videoId;
g.mI()&&g.jI("yt-remote-session-video-id",a)},this)},a8=function(a){b7("conn",a)},SFa=function(a,b){return new W6(Z6(a.sa,"/bc"),b)},b8=function(a,b){a.V("proxyStateChange",b)},TFa=function(a){a.D=g.SE((0,g.A)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.UE(a.D);
a.D=NaN},d8=function(a){g.UE(a.R);
a.R=NaN},UFa=function(a){e8(a);
a.L=g.SE((0,g.A)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.UE(a.L);
a.L=NaN},WFa=function(a,b){b&&(c8(a),d8(a));
b==(X6(a.o)&&isNaN(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Z()&&a.qb.reset(),b8(a,1),f8(a,"getNowPlaying"),VFa(a)):a.F(1)},XFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.qb.videoId&&(g.cc(b.params)?a.qb.o=null:a.qb.o=b.params,a.V("remotePlayerChange"))},YFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.qb.listId=b.params.listId||a.qb.listId;Q7(a.qb,c,d);a.V("remoteQueueChange")},$Fa=function(a,b){b.params=b.params||{};
YFa(a,b);ZFa(a,b);a.V("autoplayDismissed")},ZFa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
N7(a.qb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.qb.playerState&&(c=-1E3);a.qb.playerState=c;c=Number(b.params.loadedTime);a.qb.J=isNaN(c)?0:c;c=Number(b.params.duration);a.qb.G=isNaN(c)?0:c;c=a.qb;var d=Number(b.params.liveIngestionTime);c.A=d;c.H=isNaN(d)?!1:!0;c=a.qb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.F=isNaN(e)?0:e;1==a.qb.playerState?UFa(a):e8(a);a.V("remotePlayerChange")},aGa=function(a,b){if(-1E3!=
a.qb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.qb.playerState=c;c=parseInt(b.params.currentTime,10);N7(a.qb,isNaN(c)?0:c);a.V("remotePlayerChange")}},bGa=function(a,b){var c="true"==b.params.muted;
a.qb.volume=parseInt(b.params.volume,10);a.qb.muted=c;a.V("remotePlayerChange")},cGa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},dGa=function(a,b){var c="true"==b.params.hasNext;
a.qb.Yf="true"==b.params.hasPrevious;a.qb.hasNext=c;a.V("previousNextChange")},VFa=function(a){g.UE(a.K);
a.K=g.SE((0,g.A)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.Xg(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){f7.call(this,"ScreenServiceProxy");
this.kd=a;this.A=[];this.A.push(this.kd.$_s("screenChange",(0,g.A)(this.NW,this)));this.A.push(this.kd.$_s("onlineScreenChange",(0,g.A)(this.KS,this)))},iGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.KE("MDX_CONFIG")||b;mEa();p6();h8||(h8=new Y6(b?b.loungeApiHost:void 0),uEa()&&(h8.o="/api/loungedev"));i8||(i8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ca("yt.mdx.remote.deferredProxies_",i8,void 0));eGa();var c=j8();if(!c){var d=new o7(h8);g.Ca("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);JFa(a,d,function(a){a?k8()&&J7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){d6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ca("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.Xg(b)),m8.push(g.ZE("yt-remote-cast2-availability-change",function(){d6("yt-remote-receiver-availability-change")})),m8.push(g.ZE("yt-remote-cast2-receiver-selected",function(){n8(null);
d6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.ZE("yt-remote-cast2-receiver-resumed",function(){d6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.ZE("yt-remote-cast2-session-change",fGa)),m8.push(g.ZE("yt-remote-connection-change",function(a){a?J7(k8(),"YouTube TV"):o8()||(J7(null,null),MFa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.mF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.Xg(a)),gGa(a),c.start(),k8()||hGa())},kGa=function(){var a=jGa();
G7()&&g.kI("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},jGa=function(){var a=j8().kd.$_gos();
var b=q8();b&&r8()&&(k6(a,b)||a.push(b));return lEa(a)},s8=function(){var a=lGa();
!a&&G7()&&LFa()&&(a={key:"cast-selector-receiver",name:LFa()});return a},lGa=function(){var a=jGa(),b=q8();
b||(b=o8());return g.Sa(a,function(a){return b&&g6(b,a.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().ze();return l6(b,a)},fGa=function(a){l8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=q8();b&&b.id==a.id?J7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){H7()?E7().stopSession():C7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){b7("remote",a)},j8=function(){if(!x8){var a=g.x("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.x("yt.mdx.remote.currentScreenId_")},mGa=function(a){g.Ca("yt.mdx.remote.currentScreenId_",a,void 0)},nGa=function(){return g.x("yt.mdx.remote.connectData_")},n8=function(a){g.Ca("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.x("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||mGa("");g.Ca("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.C)(i8,function(b){b(a)}),i8.length=0);
b&&!a?d6("yt-remote-connection-change",!1):!b&&a&&d6("yt-remote-connection-change",!0)},o8=function(){var a=g.mI();
if(!a)return null;var b=j8().ze();return l6(b,a)},u8=function(a,b){q8()&&q8();
mGa(a.id);var c=new $7(h8,a,p8());c.connect(b,nGa());c.subscribe("beforeDisconnect",function(a){d6("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},hGa=function(){var a=o8();
a?(l8("Resume connection to: "+h6(a)),u8(a,0)):(q6(),MFa(),l8("Skipping connecting because no session screen found."))},eGa=function(){var a=p8();
if(g.cc(a)){a=o6();var b=g.kI("yt-remote-session-name")||"",c=g.kI("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ca("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},gGa=function(a){a?(g.jI("yt-remote-session-app",a.app),g.jI("yt-remote-session-name",a.name)):(g.lI("yt-remote-session-app"),g.lI("yt-remote-session-name"));
g.Ca("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.J.call(this);
this.D=a;this.A=b;this.B=new g.VG(this);g.K(this,this.B);this.B.O(b,"onCaptionsTrackListChanged",this.eS);this.B.O(b,"captionschanged",this.NQ);this.B.O(b,"captionssettingschanged",this.qG);this.B.O(b,"videoplayerreset",this.Hq);this.B.O(b,"mdxautoplaycancel",this.gK);this.T=this.B.O(b,"onVolumeChange",this.xE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.ME,this);c.subscribe("remotePlayerChange",this.An,this);c.subscribe("remoteQueueChange",this.Hq,this);c.subscribe("autoplayUpNext",this.jE,
this);c.subscribe("previousNextChange",this.JE,this);c.subscribe("nowAutoplaying",this.BE,this);c.subscribe("autoplayDismissed",this.iE,this);this.suggestion=null;this.J=new g.KQ(64);this.C=new g.U(this.nG,500,this);g.K(this,this.C);this.F=new g.U(this.oG,1E3,this);g.K(this,this.F);this.L=new w6(this.oW,0,this);g.K(this,this.L);this.G={};this.R=new g.U(this.PG,1E3,this);g.K(this,this.R);this.K=new g.Zl(this.IO,1E3,this);g.K(this,this.K);this.N=g.y;this.qG();this.Hq();this.An()},z8=function(a,b){a.D.Ie(b,
a.A.getVideoData().lengthSeconds)},oGa=function(a){z8(a,0);
a.C.stop();A8(a,new g.KQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.getSubtitlesUserSettings()},g.kc(c,b));a.o.bG(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.getPlaylist();
if(c){var d=c.ye();var e=c.listId.toString()}c=a.A.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.hk,dEa(c));A8(a,new g.KQ(1))},pGa=function(a,b){if(b){var c=a.A.getOption("captions","tracklist",{N4:1});
c&&c.length?(a.A.setOption("captions","track",b),a.H=!1):(a.A.loadModule("captions"),a.H=!0)}else a.A.setOption("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.QQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.UU(a.A,d);a.J=b;qGa(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
M:"ytp-remote",P:[{I:"div",M:"ytp-remote-display-status",P:[{I:"div",M:"ytp-remote-display-status-icon",P:[g.Dsa()]},{I:"div",M:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.B=new g.LV(this,250);g.K(this,this.B);this.C=a;this.O(a,"presentingplayerstatechange",this.D);rGa(this,g.QU(a))},rGa=function(a,b){if(3==a.C.getPresentingPlayerType()){var c={RECEIVER_NAME:a.C.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.DV("Error on $RECEIVER_NAME",c):b.tb()||g.X(b,4)?g.DV("Playing on $RECEIVER_NAME",c):g.DV("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.bX.call(this,"Play on",0,a,b);
this.B=a;this.H={};this.O(a,"onMdxReceiversChange",this.L);this.O(a,"presentingplayerstatechange",this.L);this.L()},G8=function(a){g.nV.call(this,a);
this.A={key:j6(),name:"This computer"};this.C=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.B=this.A;this.hn=new g.KQ(64);this.J=0;this.H=-1;if(!g.HN(g.Y(this.player))){a=this.player;var b=g.zQ(a);b&&(b=b.kn())&&(b=new F8(a,b),g.K(this,b));b=new E8(a);g.K(this,b);g.eV(a,b.element,4)}},qGa=function(a,b,c){a.hn=c;
a.player.V("presentingplayerstatechange",new g.UQ(c,b))},H8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)t8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Aa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.hk,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=dEa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.Xg(b));"cast-selector-receiver"==b.key?
(n8(d||null),H7()?E7().setLaunchParams(d||null):C7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?d6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().ze(),(d=l6(d,b.key))&&u8(d,1))}},GEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},G6={"'":"\\'"},sGa={},hEa={lY:"atp",Q2:"ska",e2:"que",o1:"mus",M2:"sus",x_:"dsp",w2:"seq"};
e6.prototype.ph=function(){var a=new e6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var r6,n6="",v6=s6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",yEa=s6("loadCastFramework")||s6("loadCastApplicationFramework"),IFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(w6,g.J);g.h=w6.prototype;g.h.fL=function(a){this.C=arguments;this.o=!1;this.Ia?this.B=(0,g.H)()+this.Gd:this.Ia=g.Sg(this.D,this.Gd)};
g.h.stop=function(){this.Ia&&(g.Tg(this.Ia),this.Ia=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.W=function(){this.stop();w6.ga.W.call(this)};
g.h.gL=function(){this.B?(this.Ia=g.Sg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ia=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};x6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
x6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=y6.prototype;g.h.Gi=null;g.h.Ff=!1;g.h.vl=null;g.h.my=null;g.h.Sk=null;g.h.Wj=null;g.h.zh=null;g.h.Yh=null;g.h.ij=null;g.h.Vc=null;g.h.Un=0;g.h.Hf=null;g.h.Xr=null;g.h.Ah=null;g.h.Em=-1;g.h.JF=!0;g.h.mi=!1;g.h.yu=0;g.h.Xq=null;var EEa={},B6={};g.h=y6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.lV=function(a){a=a.target;var b=this.Xq;b&&3==g.jy(a)?b.Am():this.ZG(a)};
g.h.ZG=function(a){try{if(a==this.Vc)a:{var b=g.jy(this.Vc),c=this.Vc.A,d=this.Vc.getStatus();if(g.be&&!g.Mc(10)||g.de&&!g.Lc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Hf&&!g.ny(this.Vc))break a;this.mi||4!=b||7==c||(8==c||0>=d?this.o.zf(3):this.o.zf(2));I6(this);var e=this.Vc.getStatus();this.Em=e;var f=g.ny(this.Vc);(this.Ff=200==e)?(4==b&&E6(this),this.D?(FEa(this,b,f),g.Hf&&this.Ff&&3==b&&(this.Y.X(this.A,"tick",this.gV),this.A.start())):D6(this,f),this.Ff&&!this.mi&&(4==b?this.o.Fq(this):
(this.Ff=!1,A6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ah=3,C6(13)):(this.Ah=0,C6(14)),E6(this),F6(this))}}catch(k){this.Vc&&g.ny(this.Vc)}finally{}};
g.h.gV=function(){var a=g.jy(this.Vc),b=g.ny(this.Vc);this.Un<b.length&&(I6(this),FEa(this,a,b),this.Ff&&4!=a&&A6(this))};
g.h.rU=function(a){H6((0,g.A)(this.qU,this,a),0)};
g.h.qU=function(a){this.mi||(I6(this),D6(this,a),A6(this))};
g.h.UE=function(a){H6((0,g.A)(this.pU,this,a),0)};
g.h.pU=function(a){this.mi||(E6(this),this.Ff=a,this.o.Fq(this),this.o.zf(4))};
g.h.cancel=function(){this.mi=!0;E6(this)};
g.h.GU=function(){this.vl=null;var a=(0,g.H)();0<=a-this.my?(2!=this.Wj&&this.o.zf(3),E6(this),this.Ah=2,C6(18),F6(this)):IEa(this,this.my-a)};
g.h.getLastError=function(){return this.Ah};g.h=LEa.prototype;g.h.wu=null;g.h.oe=null;g.h.Yq=!1;g.h.FB=null;g.h.ep=null;g.h.Cv=null;g.h.xu=null;g.h.Xe=null;g.h.Rg=-1;g.h.Dm=null;g.h.Ml=null;g.h.connect=function(a){this.xu=a;a=K6(this.o,null,this.xu);C6(3);this.FB=(0,g.H)();var b=this.o.H;null!=b?(this.Dm=b[0],(this.Ml=b[1])?(this.Xe=1,MEa(this)):(this.Xe=2,M6(this))):(c6(a,"MODE","init"),this.oe=new y6(this,void 0,void 0,void 0),this.oe.Gi=this.wu,z6(this.oe,a,!1,null,!0),this.Xe=0)};
g.h.hK=function(a){if(a)this.Xe=2,M6(this);else{C6(4);var b=this.o;b.Uf=b.oh.Rg;T6(b,9)}a&&this.zf(2)};
g.h.Pt=function(a){return this.o.Pt(a)};
g.h.abort=function(){this.oe&&(this.oe.cancel(),this.oe=null);this.Rg=-1};
g.h.EB=function(){return!1};
g.h.NE=function(a,b){this.Rg=a.Em;if(0==this.Xe)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Uf=this.Rg;T6(c,2);return}this.Dm=c[0];this.Ml=c[1]}else c=this.o,c.Uf=this.Rg,T6(c,2);else if(2==this.Xe)if(this.Yq)C6(7),this.Cv=(0,g.H)();else if("11111"==b){if(C6(6),this.Yq=!0,this.ep=(0,g.H)(),c=this.ep-this.FB,!g.be||g.Mc(10)||500>c)this.Rg=200,this.oe.cancel(),C6(12),L6(this.o,this,!0)}else C6(8),this.ep=this.Cv=(0,g.H)(),this.Yq=!1};
g.h.Fq=function(){this.Rg=this.oe.Em;if(this.oe.Ff)0==this.Xe?this.Ml?(this.Xe=1,MEa(this)):(this.Xe=2,M6(this)):2==this.Xe&&((!g.be||g.Mc(10)?!this.Yq:200>this.Cv-this.ep)?(C6(11),L6(this.o,this,!1)):(C6(12),L6(this.o,this,!0)));else{0==this.Xe?C6(9):2==this.Xe&&C6(10);var a=this.o;this.oe.getLastError();a.Uf=this.Rg;T6(a,2)}};
g.h.Mn=function(){return this.o.Mn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.zf=function(a){this.o.zf(a)};g.h=N6.prototype;g.h.fm=null;g.h.ie=null;g.h.Ac=null;g.h.vu=null;g.h.gp=null;g.h.Vz=null;g.h.xp=null;g.h.un=0;g.h.fQ=0;g.h.Fd=null;g.h.th=null;g.h.Eg=null;g.h.si=null;g.h.oh=null;g.h.Ur=null;g.h.qk=-1;g.h.wC=-1;g.h.Uf=-1;g.h.Nj=0;g.h.Ej=0;g.h.pi=8;var U6=new g.gg;g.B(OEa,g.Ff);g.B(PEa,g.Ff);g.B(QEa,g.Ff);g.h=N6.prototype;g.h.connect=function(a,b,c,d,e){C6(0);this.vu=b;this.fm=c||{};d&&g.za(e)&&(this.fm.OSID=d,this.fm.OAID=e);this.F?(H6((0,g.A)(this.oA,this,a),100),UEa(this)):this.oA(a)};
g.h.oA=function(a){this.oh=new LEa(this);this.oh.wu=null;this.oh.A=this.D;this.oh.connect(a)};
g.h.EB=function(){return 0==this.o};
g.h.TE=function(a){this.th=null;XEa(this,a)};
g.h.SE=function(){this.Eg=null;this.Ac=new y6(this,this.B,"rpc",this.G);this.Ac.Gi=null;this.Ac.yu=0;var a=this.Vz.clone();g.Dn(a,"RID","rpc");g.Dn(a,"SID",this.B);g.Dn(a,"CI",this.Ur?"0":"1");g.Dn(a,"AID",this.qk);O6(this,a);if(!g.be||g.Mc(10))g.Dn(a,"TYPE","xmlhttp"),z6(this.Ac,a,!0,this.xp,!1);else{g.Dn(a,"TYPE","html");var b=this.Ac,c=!!this.xp;b.Wj=3;b.zh=b6(a.clone());HEa(b,c)}};
g.h.NE=function(a,b){if(0!=this.o&&(this.Ac==a||this.ie==a))if(this.Uf=a.Em,this.ie==a&&3==this.o)if(7<this.pi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Fa(c)&&3==c.length)if(0==c[0])a:{if(!this.Eg){if(this.Ac)if(this.Ac.Sk+3E3<this.ie.Sk)Q6(this),this.Ac.cancel(),this.Ac=null;else break a;S6(this);C6(19)}}else this.wC=c[1],0<this.wC-this.qk&&37500>c[2]&&this.Ur&&0==this.Ej&&!this.si&&(this.si=H6((0,g.A)(this.IQ,this),6E3));else T6(this,11)}else b!=sGa.oZ.o&&T6(this,11);else if(this.Ac==a&&
Q6(this),!g.D(b)){c=this.D.parse(b);g.Fa(c);for(var d=0;d<c.length;d++){var e=c[d];this.qk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.xp=e[2],e=e[3],null!=e?this.pi=e:this.pi=6,this.o=3,this.Fd&&this.Fd.iA(),this.Vz=K6(this,this.Mn()?this.xp:null,this.vu),YEa(this)):"stop"==e[0]&&T6(this,7):3==this.o&&("stop"==e[0]?T6(this,7):"noop"!=e[0]&&this.Fd&&this.Fd.hA(e),this.Ej=0)}}};
g.h.IQ=function(){null!=this.si&&(this.si=null,this.Ac.cancel(),this.Ac=null,S6(this),C6(20))};
g.h.Fq=function(a){if(this.Ac==a){Q6(this);this.Ac=null;var b=2}else if(this.ie==a)this.ie=null,b=1;else return;this.Uf=a.Em;if(0!=this.o)if(a.Ff)1==b?(b=(0,g.H)()-a.Sk,U6.dispatchEvent(new PEa(U6,a.ij?a.ij.length:0,b,this.Nj)),P6(this),this.C.length=0):YEa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Uf)){if(d=1==b)this.ie||this.th||1==this.o||2<=this.Nj?d=!1:(this.th=H6((0,g.A)(this.TE,this,a),ZEa(this,this.Nj)),this.Nj++,d=!0);d=!(d||2==b&&S6(this))}if(d)switch(c){case 1:T6(this,
5);break;case 4:T6(this,10);break;case 3:T6(this,6);break;case 7:T6(this,12);break;default:T6(this,2)}}};
g.h.EK=function(a){if(!g.Wa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.eW=function(a){a?C6(2):(C6(1),$Ea(this,8))};
g.h.Pt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.dy;a.H=!1;return a};
g.h.isActive=function(){return!!this.Fd&&this.Fd.isActive(this)};
g.h.zf=function(a){U6.dispatchEvent(new QEa(U6,a))};
g.h.Mn=function(){return!(!g.be||g.Mc(10))};
g.h=aFa.prototype;g.h.iA=function(){};
g.h.hA=function(){};
g.h.gA=function(){};
g.h.Bt=function(){};
g.h.jB=function(){return{}};
g.h.isActive=function(){return!0};g.B(V6,g.J);g.h=V6.prototype;g.h.hU=function(){this.Gd=Math.min(3E5,2*this.Gd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Gd+15E3*Math.random();g.cv(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Gd=5E3};g.B(W6,aFa);g.h=W6.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.xk=function(a){return this.B.Hi(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.Cb||(this.Cb=!0,g.Df(this.B),dFa(this),g.Df(this.A),this.A=null)};
g.h.la=function(){return this.Cb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new N6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.Fd=null);d.Fd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.qk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.kc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):X6(this)&&VEa(this.o,c)};
g.h.iA=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)VEa(this.o,a[b])}this.V("handlerOpened")};
g.h.gA=function(a){var b=2==a&&401==this.o.Uf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Bt=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.jB=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.kc(a,this.D);return a};
g.h.hA=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),TEa(this.o)):this.V("handlerMessage",new bFa(a[0],a[1]))};
g.h.JW=function(){this.A.isActive();var a=this.o,b=0;a.Ac&&b++;a.ie&&b++;0!=b||this.connect(this.D,this.C)};Y6.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Y6.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Y6.prototype.D=function(a){a(Error("request timed out"))};var lFa=(0,g.H)(),a7=null,d7=Array(50),c7=-1,e7=!1;g.B(f7,g.V);f7.prototype.ze=function(){return this.o};
f7.prototype.contains=function(a){return!!k6(this.o,a)};
f7.prototype.get=function(a){return a?l6(this.o,a):null};
f7.prototype.info=function(a){b7(this.G,a)};g.B(g7,g.V);var tGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=g7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ia)&&this.bH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ia)||(g.UE(this.Ia),this.Ia=NaN)};
g.h.W=function(){this.stop();g7.ga.W.call(this)};
g.h.bH=function(){this.Ia=NaN;this.o=g.EF(Z6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.LW,this),onError:(0,g.A)(this.KW,this),Kd:(0,g.A)(this.MW,this)})};
g.h.LW=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new f6(c))};
g.h.KW=function(a){this.o=null;a.status&&404==a.status?this.A>=tGa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=tGa[this.A],this.Ia=g.SE((0,g.A)(this.bH,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.MW=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(i7,f7);g.h=i7.prototype;g.h.start=function(){h7(this)&&this.V("screenChange");!g.kI("yt-remote-lounge-token-expiration")&&pFa(this);g.UE(this.A);this.A=g.SE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){h7(this);mFa(this,a);j7(this,!1);this.V("screenChange");b(a);a.token||pFa(this)};
g.h.remove=function(a,b){var c=h7(this);oFa(this,a)&&(j7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Qr=function(a,b,c,d){var e=h7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,j7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.W=function(){g.UE(this.A);i7.ga.W.call(this)};
g.h.uL=function(a){h7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}j7(this,!b);b&&b7(this.G,"Missed "+b+" lounge tokens.")};
g.h.tL=function(a){b7(this.G,"Requesting lounge tokens failed: "+a)};g.B(l7,g.V);g.h=l7.prototype;g.h.start=function(){var a=parseInt(g.kI("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?n7(this):(this.C=(0,g.H)()+3E5,g.jI("yt-remote-fast-check-period",this.C),this.ix())};
g.h.isEmpty=function(){return g.cc(this.o)};
g.h.update=function(){k7("Updating availability on schedule.");var a=this.F(),b=g.Mb(this.o,function(b,d){return b&&!!l6(a,d)},this);
m7(this,b)};
g.h.W=function(){g.UE(this.B);this.B=NaN;this.A&&(this.A.abort(),this.A=null);l7.ga.W.call(this)};
g.h.ix=function(){g.UE(this.B);this.B=NaN;this.A&&this.A.abort();var a=sFa(this);if(g.Rb(a)){var b=Z6(this.D,"/pairing/get_screen_availability");this.A=$6(this.D,b,{lounge_token:g.Ub(a).join(",")},(0,g.A)(this.NT,this,a),(0,g.A)(this.LT,this))}else m7(this,{}),n7(this)};
g.h.NT=function(a,b){this.A=null;var c=g.Ub(sFa(this));if(g.sb(c,g.Ub(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;m7(this,d);n7(this)}else this.sc("Changing Screen set during request."),this.ix()};
g.h.LT=function(a){this.sc("Screen availability failed: "+a);this.A=null;n7(this)};
g.h.sc=function(a){b7("OnlineScreenService",a)};g.B(o7,f7);g.h=o7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Qr=function(a,b,c,d){this.B.contains(a)?this.B.Qr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,b7(this.G,a),d(Error(a)))};
g.h.ze=function(a){return a?this.o:g.db(this.o,(0,g.pe)(this.C,function(a){return!this.contains(a)},this))};
g.h.cH=function(){return(0,g.pe)(this.ze(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.dH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new g7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Df(f);d(p7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Df(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.OW=function(a,b,c,d){g.EF(Z6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new f6(d.screen||{});if(!e.name||wFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);wFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(p7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Kd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Df(this.B);g.Df(this.A);o7.ga.W.call(this)};
g.h.IL=function(){xFa(this);this.V("screenChange");this.A.update()};
o7.prototype.dispose=o7.prototype.dispose;g.B(r7,g.V);g.h=r7.prototype;g.h.Gq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Ee=function(a){this.la()||(a&&s7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){b7(this.R,a)};
g.h.fH=function(){return null};
g.h.yx=function(a){var b=this.A;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){s7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.yx("");r7.ga.W.call(this)};g.B(t7,r7);g.h=t7.prototype;g.h.xx=function(a){if(this.o){if(this.o==a)return;s7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);zFa(this)};
g.h.tk=function(a){this.info("launchWithParams no-op for Cast: "+g.Xg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.Ee()},this),(0,g.A)(function(){this.Ee(Error("Failed to stop receiver app."))},this)):this.Ee(Error("Stopping cast device witout session."))};
g.h.yx=g.y;g.h.W=function(){this.info("disposeInternal");g.UE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;t7.ga.W.call(this)};
g.h.SU=function(a,b){if(!this.la())if(b){var c=g.Zx(b);if(g.Ia(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Xg(c));switch(d){case "mdxSessionStatus":yFa(this,c.screenId);break;default:s7(this,"Unknown youtube message: "+d)}}else s7(this,"Unable to parse message.")}else s7(this,"No data in message.")};
g.h.uB=function(a,b,c,d){vFa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(s7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.SE((0,g.A)(this.uB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.fH=function(){return this.o};
g.h.PW=function(a){this.la()||a||(s7(this,"Cast session died."),this.Ee())};g.B(u7,r7);g.h=u7.prototype;g.h.xx=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.tk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.y;g.UE(this.F);this.C?this.C.stop((0,g.A)(this.Ee,this,null),(0,g.A)(this.Ee,this,"Failed to stop DIAL device.")):this.Ee()};
g.h.W=function(){this.o();this.o=g.y;g.UE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;u7.ga.W.call(this)};
g.h.SW=function(a){this.la()||a||(s7(this,"DIAL session died."),this.o(),this.o=g.y,this.Ee())};
g.h.Zu=function(a){this.K=j6();if(this.D){var b=new chrome.cast.DialLaunchResponse(!0,BFa(this));a(b);AFa(this)}else this.G=(0,g.A)(function(){g.UE(this.F);this.G=g.y;this.F=NaN;var b=new chrome.cast.DialLaunchResponse(!0,BFa(this));a(b);AFa(this)},this),this.F=g.SE((0,g.A)(function(){this.G()},this),100)};
g.h.UM=function(a,b,c){vFa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Gq(a),b(new chrome.cast.DialLaunchResponse(!1))):this.Zu(b,c)},this),(0,g.A)(function(a){s7(this,"Failed to get DIAL screen: "+a);
this.Zu(b,c)},this))};g.B(v7,r7);v7.prototype.stop=function(){this.Ee()};
v7.prototype.xx=g.y;v7.prototype.tk=function(){g.UE(this.o);this.o=NaN;var a=l6(this.J.ze(),this.A.label);a?this.Gq(a):this.Ee(Error("No such screen"))};
v7.prototype.W=function(){g.UE(this.o);this.o=NaN;v7.ga.W.call(this)};g.B(w7,g.V);g.h=w7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.A)(this.PE,this),(0,g.A)(this.uT,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.qR,this);chrome.cast.initialize(c,(0,g.A)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.C),iFa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.eH,this)),this.B=DFa(this),chrome.cast.setCustomReceivers(this.B,g.y,(0,g.A)(function(a){this.sc("Failed to set initial custom receivers: "+g.Xg(a))},this)),this.V("yt-remote-cast2-availability-change",y7(this)),b(!0))},this),(0,g.A)(function(a){this.sc("Failed to initialize API: "+g.Xg(a));
b(!1)},this))};
g.h.MV=function(a,b){x7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)x7("Unsetting old screen status: "+this.o.A.friendlyName),z7(this,null)}if(a&&b){if(!this.o){c=l6(this.A.ze(),a);if(!c){x7("setConnectedScreenStatus: Unknown screen.");return}var d=CFa(this,c);d||(x7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(d),chrome.cast.setCustomReceivers(this.B,
g.y,(0,g.A)(function(a){this.sc("Failed to set initial custom receivers: "+g.Xg(a))},this)));
x7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);z7(this,new v7(this.A,d),!0)}this.o.yx(b)}else x7("setConnectedScreenStatus: no screen.")};
g.h.NV=function(a){this.la()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.tk(a):this.sc("Setting connection data without a session")};
g.h.RW=function(){this.la()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),z7(this,null)):x7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.PE,this),(0,g.A)(this.RT,this))};
g.h.W=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.eH,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);g.ab(g.x("yt.mdx.remote.debug.handlers_")||[],fFa);g.Df(this.o);w7.ga.W.call(this)};
g.h.sc=function(a){b7("Controller",a)};
g.h.QE=function(a,b){this.o==a&&(b||z7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.qT=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),x7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)x7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{x7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:z7(this,
new v7(this.A,a));break;case chrome.cast.ReceiverType.DIAL:z7(this,new u7(this.A,a,this.F));break;case chrome.cast.ReceiverType.CAST:z7(this,new t7(this.A,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.h.qR=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.B)return x7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);z7(this,new u7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.UM,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.A)(b.Zu,b))};
g.h.PE=function(a){if(!this.la()){x7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)x7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),z7(this,new t7(this.A,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=l6(this.A.ze(),c.label);d&&g6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(x7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Df(this.o),this.o=new t7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.QE,this,this.o)),this.o.tk(null));this.o.xx(a)}}};
g.h.QW=function(){return this.o?this.o.fH():null};
g.h.RT=function(a){this.la()||(this.sc("Failed to estabilish a session: "+g.Xg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&z7(this,null))};
g.h.uT=function(a){x7("Receiver availability updated: "+a);if(!this.la()){var b=y7(this);this.D=a==chrome.cast.ReceiverAvailability.AVAILABLE;y7(this)!=b&&this.V("yt-remote-cast2-availability-change",y7(this))}};
g.h.eH=function(){this.la()||(this.B=DFa(this),x7("Updating custom receivers: "+g.Xg(this.B)),chrome.cast.setCustomReceivers(this.B,g.y,(0,g.A)(function(){this.sc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",y7(this)))};
w7.prototype.setLaunchParams=w7.prototype.NV;w7.prototype.setConnectedScreenStatus=w7.prototype.MV;w7.prototype.stopSession=w7.prototype.RW;w7.prototype.getCastSession=w7.prototype.QW;w7.prototype.requestSession=w7.prototype.requestSession;w7.prototype.init=w7.prototype.init;w7.prototype.dispose=w7.prototype.dispose;var F7=[];g.h=K7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";L7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Yf=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.C=a.playerTimeAt,this.B=a.seekableStart,this.F=a.seekableEnd,this.G=a.duration,this.J=a.loadedTime,this.A=a.liveIngestionTime,this.H=!isNaN(this.A))};
g.h.tb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.H?this.G+M7(this):this.G};
g.h.clone=function(){return new K7(R7(this))};g.B(T7,g.V);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.y,Z7(this,"play")):Y7(this,"play"),X7(this,1,O7(U7(this))),this.V("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.y,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,O7(U7(this))),this.V("remotePlayerChange")):V7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.tb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.y,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.V("remotePlayerChange")}else V7(this,g.La(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.y,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";L7(a);W7(this,a);this.V("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){b7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){b7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.La(this.setVolume,a,b))};
g.h.bG=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Xg(b.style),g.kc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.La(this.bG,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Qb.id});var c=U7(this);c.audioTrackId=b.Qb.id;W7(this,c)}else V7(this,g.La(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=U7(this);c=c||0;var m={videoId:a,currentIndex:c};Q7(l,a,c);g.za(b)&&(N7(l,b),m.currentTime=b);g.za(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Xg(k));Y7(this,"setPlaylist",m);d||W7(this,l)};
g.h.Nq=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.La(this.Nq,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.La(this.nextVideo,a,b))};
g.h.IA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.IA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}T7.ga.dispose.call(this)};
g.h.W=function(){QFa(this);this.C=null;this.D.clear();S7(this,null);T7.ga.W.call(this)};
g.h.yy=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.rD(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.lT=function(a,b){this.V(a,b)};
g.h.PQ=function(a){if(!a)this.xn(null),S7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)b7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.xn=function(a){b7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),RFa(this),this.V("remotePlayerChange")};
g.h.OQ=function(a){a?(RFa(this),this.V("remotePlayerChange")):this.xn(null)};
g.h.Mx=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.bR=function(){var a=NFa();a&&S7(this,a)};
g.h.sc=function(a){b7("CP",a)};g.B($7,g.V);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.za(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.za(k)&&(l.currentIndex=k);c&&(this.qb.listId=c);this.qb.videoId=d;this.qb.index=k||0;this.qb.state=3;N7(this.qb,m);this.C="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.Xg(l));this.o.connect({method:"setPlaylist",
params:g.Xg(l)},a,pEa())}else a8("Connecting without params"),this.o.connect({},a,pEa());TFa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),b8(this,3));$7.ga.dispose.call(this)};
g.h.W=function(){c8(this);e8(this);d8(this);g.UE(this.J);this.J=NaN;g.UE(this.K);this.K=NaN;this.B=null;g.HG(this.T);this.T.length=0;this.o.dispose();$7.ga.W.call(this);this.C=this.G=this.A=this.qb=this.o=null};
g.h.kL=function(){this.F(2)};
g.h.TQ=function(){a8("Channel opened");this.N&&(this.N=!1,d8(this),this.R=g.SE((0,g.A)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
tEa(cFa(this.o),this.aa)};
g.h.QQ=function(){a8("Channel closed");isNaN(this.D)?q6(!0):q6();this.dispose()};
g.h.RQ=function(a){q6();isNaN(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.SQ=function(a){a.params?a8("Received: action="+a.action+", params="+g.Xg(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Zx(a.params.devices);this.A=(0,g.I)(a,function(a){return new e6(a)});
a=!!g.Sa(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
WFa(this,a);break;case "loungeScreenDisconnected":g.bb(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
WFa(this,!1);break;case "remoteConnected":var b=new e6(g.Zx(a.params.device));g.Sa(this.A,function(a){return b?a.id==b.id:!1})||g.Za(this.A,b);
break;case "remoteDisconnected":b=new e6(g.Zx(a.params.device));g.bb(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":YFa(this,a);break;case "nowPlaying":$Fa(this,a);break;case "onStateChange":ZFa(this,a);break;case "onAdStateChange":aGa(this,a);break;case "onVolumeChanged":bGa(this,a);break;case "onSubtitlesTrackChanged":XFa(this,a);break;case "nowAutoplaying":cGa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":dGa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.tV=function(){if(this.B){var a=this.B;this.B=null;this.qb.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.xk;$7.prototype.ha=function(){var a=3;this.la()||(a=0,isNaN(this.H())?X6(this.o)&&isNaN(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ha;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.V("beforeDisconnect",a);1==a&&q6();dFa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.fa=function(){var a=this.qb;this.B&&(a=this.qb.clone(),Q7(a,this.B,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.fa;
$7.prototype.ma=function(a){var b=new K7(a);b.videoId&&b.videoId!=this.qb.videoId&&(this.B=b.videoId,g.UE(this.J),this.J=g.SE((0,g.A)(this.tV,this),5E3));var c=[];this.qb.listId==b.listId&&this.qb.videoId==b.videoId&&this.qb.index==b.index||c.push("remoteQueueChange");this.qb.playerState==b.playerState&&this.qb.volume==b.volume&&this.qb.muted==b.muted&&O7(this.qb)==O7(b)&&g.Xg(this.qb.o)==g.Xg(b.o)||c.push("remotePlayerChange");this.qb.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Z=function(){var a=this.o.F.id,b=g.Sa(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Z;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.ea=function(){return this.C||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.ea;$7.prototype.da=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.da;$7.prototype.ya=function(){if(!isNaN(this.H())){var a=this.o.A;g.dv(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.ya;$7.prototype.ka=function(a,b){f8(this,a,b);VFa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.B(g8,f7);g.h=g8.prototype;g.h.ze=function(a){return this.kd.$_gs(a)};
g.h.contains=function(a){return!!this.kd.$_c(a)};
g.h.get=function(a){return this.kd.$_g(a)};
g.h.start=function(){this.kd.$_st()};
g.h.add=function(a,b,c){this.kd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.kd.$_r(a,b,c)};
g.h.Qr=function(a,b,c,d){this.kd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.A.length;a<b;++a)this.kd.$_ubk(this.A[a]);this.A.length=0;this.kd=null;g8.ga.W.call(this)};
g.h.NW=function(){this.V("screenChange")};
g.h.KS=function(){this.V("onlineScreenChange")};
o7.prototype.$_st=o7.prototype.start;o7.prototype.$_gspc=o7.prototype.OW;o7.prototype.$_gsppc=o7.prototype.dH;o7.prototype.$_c=o7.prototype.contains;o7.prototype.$_g=o7.prototype.get;o7.prototype.$_a=o7.prototype.add;o7.prototype.$_un=o7.prototype.Qr;o7.prototype.$_r=o7.prototype.remove;o7.prototype.$_gs=o7.prototype.ze;o7.prototype.$_gos=o7.prototype.cH;o7.prototype.$_s=o7.prototype.subscribe;o7.prototype.$_ubk=o7.prototype.xk;var h8=null,i8=null,x8=null,m8=[];g.r(y8,g.J);g.h=y8.prototype;
g.h.W=function(){g.J.prototype.W.call(this);this.C.stop();this.F.stop();this.L.stop();this.N();this.o.unsubscribe("proxyStateChange",this.ME,this);this.o.unsubscribe("remotePlayerChange",this.An,this);this.o.unsubscribe("remoteQueueChange",this.Hq,this);this.o.unsubscribe("autoplayUpNext",this.jE,this);this.o.unsubscribe("previousNextChange",this.JE,this);this.o.unsubscribe("nowAutoplaying",this.BE,this);this.o.unsubscribe("autoplayDismissed",this.iE,this);this.o=this.D=null};
g.h.kD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).tb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Am(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,c)}};
g.h.NQ=function(a){this.L.fL(a)};
g.h.oW=function(a){this.kD("control_subtitles_set_track",g.cc(a)?null:a)};
g.h.qG=function(){var a=this.A.getOption("captions","track");g.cc(a)||C8(this,a)};
g.h.xE=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.An,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.R.start();this.o.subscribe("remotePlayerChange",this.An,this)}};
g.h.eS=function(){g.cc(this.G)||pGa(this,this.G);this.H=!1};
g.h.ME=function(a,b){this.F.stop();2==b&&this.oG()};
g.h.An=function(){if(B8(this)){this.C.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.Wk(1);break;case 1082:case 1083:this.D.Wk(0);break;default:this.D.Wk(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.KQ(8));this.nG();break;case 1085:case 3:A8(this,new g.KQ(9));break;case 1083:case 0:A8(this,new g.KQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.KQ(4));break;case 2:A8(this,new g.KQ(4));z8(this,O7(a));
break;case -1:A8(this,new g.KQ(64));break;case -1E3:A8(this,new g.KQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.G=a,pGa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.R.isActive()||this.PG()}else oGa(this)};
g.h.JE=function(){this.A.V("mdxpreviousnextchange")};
g.h.Hq=function(){B8(this)||oGa(this)};
g.h.gK=function(){this.o.IA()};
g.h.jE=function(a){a&&(a=g.EF("/watch_queue_ajax",{method:"GET",dd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.tU,this)}))&&(this.N=(0,g.A)(a.abort,a))};
g.h.tU=function(a,b){var c=new g.EP(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.BE=function(a){isNaN(a)||this.A.V("mdxnowautoplaying",a)};
g.h.iE=function(){this.A.V("mdxautoplaycanceled")};
g.h.IO=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.seekTo(a)};
g.h.PG=function(){if(B8(this)){var a=U7(this.o);this.B.La(this.T);a.muted?this.A.mute():this.A.unMute();this.A.setVolume(a.volume);this.T=this.B.O(this.A,"onVolumeChange",this.xE)}};
g.h.nG=function(){this.C.stop();if(!this.o.la()){var a=U7(this.o);a.tb()&&A8(this,new g.KQ(8));z8(this,O7(a));this.C.start()}};
g.h.oG=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.F.start()};g.r(E8,g.W);E8.prototype.D=function(a){rGa(this,a.state)};g.r(F8,g.bX);F8.prototype.L=function(){var a=this.B.getOption("remote","receivers");a&&1<a.length&&!this.B.getOption("remote","quickCast")?(this.H=g.ub(a,this.F,this),g.cX(this,(0,g.I)(a,this.F)),a=this.B.getOption("remote","currentReceiver"),this.yf(this.F(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.F=function(a){return a.key};
F8.prototype.xf=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
F8.prototype.Id=function(a){g.bX.prototype.Id.call(this,a);this.B.setOption("remote","currentReceiver",this.H[a]);this.C.Kb()};g.r(G8,g.nV);g.h=G8.prototype;g.h.create=function(){iGa(g.zN(g.Y(this.player)));this.D.push(g.ZE("yt-remote-before-disconnect",this.JQ,this));this.D.push(g.ZE("yt-remote-connection-change",this.vT,this));this.D.push(g.ZE("yt-remote-receiver-availability-change",this.KE,this));this.D.push(g.ZE("yt-remote-auto-connect",this.tT,this));this.D.push(g.ZE("yt-remote-receiver-resumed",this.sT,this));this.KE()};
g.h.load=function(){this.player.cancelPlayback();g.nV.prototype.load.call(this);this.C=new y8(this,this.player,this.o);var a=(a=nGa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=O7(U7(b)));0!=a&&this.Ie(a);qGa(this,this.hn,this.hn);g.C0(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.Ef(this.C,this.o);this.o=this.C=null;g.nV.prototype.unload.call(this);g.C0(this.player.app,5)};
g.h.W=function(){g.$E(this.D);g.nV.prototype.W.call(this)};
g.h.Th=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.kD.apply(this.C,[a].concat(g.ea(c)))};
g.h.Wk=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.ZK=function(){return this.loaded?this.C.suggestion:null};
g.h.Yf=function(){return this.o?U7(this.o).Yf:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.Ie=function(a,b){this.J=a||0;this.player.V("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Lc():!a.isAdPlaying()&&this.player.Lc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.H?a.A+M7(a):a.A,isPeggedToLive:1>=P7(a)-this.getCurrentTime(),isAtLiveHead:1>=P7(a)-this.getCurrentTime(),loaded:a.J,seekableEnd:P7(a),seekableStart:0<
a.B?a.B+M7(a):a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.Nq=function(){this.o&&this.o.Nq()};
g.h.JQ=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.vT=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Df(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,O7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.KE=function(){this.F=[this.A].concat(kGa());var a=s8()||this.A;H8(this,a);this.player.Ca("onMdxReceiversChange")};
g.h.tT=function(){var a=s8();H8(this,a)};
g.h.sT=function(){this.B=s8()};
g.h.Hc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?I7():H8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&I7(),!0):!1}};
g.h.Mx=function(){this.o.Mx()};
g.h.wc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.VZ.remote=G8;})(_yt_player);
